name: Binary Compatibility

on:
  pull_request:
  push:
    branches: [ main ]
    tags-ignore: [ v* ]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  check-binary-compatibility:
    name: Check / Binary Compatibility
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko-http'
    strategy:
      fail-fast: false
      matrix:
        SCALA_VERSION: [ 2.12, 2.13, 3.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 0

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile code
        run: sbt ++${{ matrix.SCALA_VERSION }} Test/compile

      - name: Report MiMa Binary Issues with Scala ${{ matrix.SCALA_VERSION }}
        run: sbt -Dpekko.http.parallelExecution=false -Dpekko.test.timefactor=2 ++${{ matrix.SCALA_VERSION }} mimaReportBinaryIssues

      - name: Check correct MiMa filter directories
        run: |
          sbt checkMimaFilterDirectories
