name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish-artifacts:
    name: Publish artifacts to Sonatype
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-http'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Publish to Apache Maven repo
        run: sbt -jvm-opts .jvmopts-ghactions +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

  publish-docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-http'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Build Documentation
        run: |-
          sbt -Dpekko.genjavadoc.enabled=true docs/paradox unidoc

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create nightly directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-http/${{ github.ref_name }}-snapshot/
          mv docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-http/${{ github.ref_name }}-snapshot/docs
          mv target/scala-2.13/unidoc target/nightly-docs/docs/pekko-http/${{ github.ref_name }}-snapshot/api
          mv target/javaunidoc target/nightly-docs/docs/pekko-http/${{ github.ref_name }}-snapshot/japi

      - name: Upload nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-http/ # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
